<?php

namespace ContainerHjoDXgH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GcZN0vfService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.gcZN0vf' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.gcZN0vf'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'university' => ['privates', '.errored..service_locator.gcZN0vf.App\\Entity\\University', NULL, 'Cannot autowire service ".service_locator.gcZN0vf": it references class "App\\Entity\\University" but no such service exists.'],
        ], [
            'university' => 'App\\Entity\\University',
        ]);
    }
}
