<?php

namespace ContainerHjoDXgH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QlZ7sQUService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qlZ7sQU' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qlZ7sQU'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'eventDispatcher' => ['services', 'event_dispatcher', 'getEventDispatcherService', false],
            'university' => ['privates', '.errored..service_locator.qlZ7sQU.App\\Entity\\University', NULL, 'Cannot autowire service ".service_locator.qlZ7sQU": it references class "App\\Entity\\University" but no such service exists.'],
        ], [
            'eventDispatcher' => '?',
            'university' => 'App\\Entity\\University',
        ]);
    }
}
