<?php

namespace ContainerHjoDXgH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KSJR8ydService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.kSJR8yd' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.kSJR8yd'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.r9uU6E5', 'get_ServiceLocator_R9uU6E5Service', true],
            'App\\Controller\\RegistrationController::verifyUserEmail' => ['privates', '.service_locator.Q1F27w5', 'get_ServiceLocator_Q1F27w5Service', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.0bwLHac', 'get_ServiceLocator_0bwLHacService', true],
            'App\\Controller\\UniversityController::addReview' => ['privates', '.service_locator.gcZN0vf', 'get_ServiceLocator_GcZN0vfService', true],
            'App\\Controller\\UniversityController::commentNew' => ['privates', '.service_locator.qlZ7sQU', 'get_ServiceLocator_QlZ7sQUService', true],
            'App\\Controller\\UniversityController::show' => ['privates', '.service_locator.gcZN0vf', 'get_ServiceLocator_GcZN0vfService', true],
            'App\\Controller\\UserController::changePassword' => ['privates', '.service_locator.83D369Q', 'get_ServiceLocator_83D369QService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.r9uU6E5', 'get_ServiceLocator_R9uU6E5Service', true],
            'App\\Controller\\RegistrationController:verifyUserEmail' => ['privates', '.service_locator.Q1F27w5', 'get_ServiceLocator_Q1F27w5Service', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.0bwLHac', 'get_ServiceLocator_0bwLHacService', true],
            'App\\Controller\\UniversityController:addReview' => ['privates', '.service_locator.gcZN0vf', 'get_ServiceLocator_GcZN0vfService', true],
            'App\\Controller\\UniversityController:commentNew' => ['privates', '.service_locator.qlZ7sQU', 'get_ServiceLocator_QlZ7sQUService', true],
            'App\\Controller\\UniversityController:show' => ['privates', '.service_locator.gcZN0vf', 'get_ServiceLocator_GcZN0vfService', true],
            'App\\Controller\\UserController:changePassword' => ['privates', '.service_locator.83D369Q', 'get_ServiceLocator_83D369QService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
        ], [
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\RegistrationController::verifyUserEmail' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\UniversityController::addReview' => '?',
            'App\\Controller\\UniversityController::commentNew' => '?',
            'App\\Controller\\UniversityController::show' => '?',
            'App\\Controller\\UserController::changePassword' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\RegistrationController:verifyUserEmail' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\UniversityController:addReview' => '?',
            'App\\Controller\\UniversityController:commentNew' => '?',
            'App\\Controller\\UniversityController:show' => '?',
            'App\\Controller\\UserController:changePassword' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
