<?php

namespace ContainerHjoDXgH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDoctrine_FixturesLoadCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'doctrine.fixtures_load_command' shared service.
     *
     * @return \Doctrine\Bundle\FixturesBundle\Command\LoadDataFixturesDoctrineCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-bundle/Command/DoctrineCommand.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-fixtures-bundle/Command/LoadDataFixturesDoctrineCommand.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/Loader.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/doctrine-bridge/DataFixtures/ContainerAwareLoader.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-fixtures-bundle/Loader/SymfonyFixturesLoader.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/FixtureInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/SharedFixtureInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/AbstractFixture.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-fixtures-bundle/ORMFixtureInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-fixtures-bundle/Fixture.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/OrderedFixtureInterface.php';
        include_once \dirname(__DIR__, 4).'/src/DataFixtures/DegreesFixtures.php';
        include_once \dirname(__DIR__, 4).'/src/DataFixtures/MajorFixtures.php';
        include_once \dirname(__DIR__, 4).'/src/DataFixtures/RatingFixtures.php';
        include_once \dirname(__DIR__, 4).'/src/DataFixtures/UniversityFixtures.php';
        include_once \dirname(__DIR__, 4).'/src/DataFixtures/UniversityMajorFixtures.php';
        include_once \dirname(__DIR__, 4).'/src/DataFixtures/UniversityRatingFixtures.php';
        include_once \dirname(__DIR__, 4).'/src/DataFixtures/UserFixtures.php';
        include_once \dirname(__DIR__, 4).'/src/DataFixtures/UserRatingFixtures.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-fixtures-bundle/Purger/PurgerFactory.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-fixtures-bundle/Purger/ORMPurgerFactory.php';

        $a = new \Doctrine\Bundle\FixturesBundle\Loader\SymfonyFixturesLoader($container);

        $b = ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService());

        $a->addFixtures([0 => ['fixture' => new \App\DataFixtures\DegreesFixtures($b), 'groups' => []], 1 => ['fixture' => new \App\DataFixtures\MajorFixtures(), 'groups' => []], 2 => ['fixture' => new \App\DataFixtures\RatingFixtures($b), 'groups' => []], 3 => ['fixture' => new \App\DataFixtures\UniversityFixtures(), 'groups' => []], 4 => ['fixture' => new \App\DataFixtures\UniversityMajorFixtures($b), 'groups' => []], 5 => ['fixture' => new \App\DataFixtures\UniversityRatingFixtures($b), 'groups' => []], 6 => ['fixture' => new \App\DataFixtures\UserFixtures(($container->services['security.password_encoder'] ?? $container->load('getSecurity_PasswordEncoderService'))), 'groups' => []], 7 => ['fixture' => new \App\DataFixtures\UserRatingFixtures($b), 'groups' => []]]);

        $container->privates['doctrine.fixtures_load_command'] = $instance = new \Doctrine\Bundle\FixturesBundle\Command\LoadDataFixturesDoctrineCommand($a, ($container->services['doctrine'] ?? $container->getDoctrineService()), ['default' => new \Doctrine\Bundle\FixturesBundle\Purger\ORMPurgerFactory()]);

        $instance->setName('doctrine:fixtures:load');

        return $instance;
    }
}
