<?php

namespace ContainerHjoDXgH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHwiOauth_ResourceOwner_FacebookService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'hwi_oauth.resource_owner.facebook' shared service.
     *
     * @return \HWI\Bundle\OAuthBundle\OAuth\ResourceOwner\FacebookResourceOwner
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/hwi/oauth-bundle/OAuth/ResourceOwnerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/hwi/oauth-bundle/OAuth/ResourceOwner/AbstractResourceOwner.php';
        include_once \dirname(__DIR__, 4).'/vendor/hwi/oauth-bundle/OAuth/ResourceOwner/GenericOAuth2ResourceOwner.php';
        include_once \dirname(__DIR__, 4).'/vendor/hwi/oauth-bundle/OAuth/ResourceOwner/FacebookResourceOwner.php';

        return $container->services['hwi_oauth.resource_owner.facebook'] = new \HWI\Bundle\OAuthBundle\OAuth\ResourceOwner\FacebookResourceOwner(($container->privates['hwi_oauth.http_client'] ?? $container->load('getHwiOauth_HttpClientService')), ($container->privates['security.http_utils'] ?? $container->getSecurity_HttpUtilsService()), ['client_id' => $container->getEnv('FB_ID'), 'client_secret' => $container->getEnv('FB_SECRET'), 'scope' => 'email', 'options' => ['display' => 'popup', 'csrf' => true], 'paths' => []], 'facebook', ($container->privates['hwi_oauth.storage.session'] ?? $container->load('getHwiOauth_Storage_SessionService')));
    }
}
