<?php

namespace ContainerHjoDXgH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHwiOauth_Authentication_Provider_Oauth_MainService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'hwi_oauth.authentication.provider.oauth.main' shared service.
     *
     * @return \HWI\Bundle\OAuthBundle\Security\Core\Authentication\Provider\OAuthProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-core/Authentication/Provider/AuthenticationProviderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/hwi/oauth-bundle/Security/Core/Authentication/Provider/OAuthProvider.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-core/User/UserProviderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/hwi/oauth-bundle/Security/Core/User/OAuthAwareUserProviderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/hwi/oauth-bundle/Security/Core/User/EntityUserProvider.php';
        include_once \dirname(__DIR__, 4).'/vendor/hwi/oauth-bundle/Connect/AccountConnectorInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Security/MyEntityUserProvider.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-core/User/UserCheckerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-core/User/UserChecker.php';

        return $container->privates['hwi_oauth.authentication.provider.oauth.main'] = new \HWI\Bundle\OAuthBundle\Security\Core\Authentication\Provider\OAuthProvider(new \App\Security\MyEntityUserProvider(($container->services['doctrine'] ?? $container->getDoctrineService()), 'App\\Entity\\User', ['facebook' => 'facebookID', 'google' => 'googleID']), ($container->services['hwi_oauth.resource_ownermap.main'] ?? $container->getHwiOauth_ResourceOwnermap_MainService()), ($container->services['hwi_oauth.user_checker'] ?? ($container->services['hwi_oauth.user_checker'] = new \Symfony\Component\Security\Core\User\UserChecker())), ($container->services['security.token_storage'] ?? $container->getSecurity_TokenStorageService()));
    }
}
