<?php

namespace ContainerHjoDXgH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHwiOauth_Http_ClientService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'hwi_oauth.http.client' shared service.
     *
     * @return \Http\Client\Common\HttpMethodsClient
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/psr/http-client/src/ClientInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/php-http/httplug/src/HttpClient.php';
        include_once \dirname(__DIR__, 4).'/vendor/php-http/client-common/src/HttpMethodsClientInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/php-http/client-common/src/HttpMethodsClient.php';
        include_once \dirname(__DIR__, 4).'/vendor/php-http/httplug/src/HttpAsyncClient.php';
        include_once \dirname(__DIR__, 4).'/vendor/php-http/client-common/src/PluginClient.php';
        include_once \dirname(__DIR__, 4).'/vendor/php-http/httplug-bundle/src/ClientFactory/ClientFactory.php';
        include_once \dirname(__DIR__, 4).'/vendor/php-http/httplug-bundle/src/Collector/ProfileClientFactory.php';
        include_once \dirname(__DIR__, 4).'/vendor/php-http/httplug-bundle/src/ClientFactory/AutoDiscoveryFactory.php';
        include_once \dirname(__DIR__, 4).'/vendor/php-http/client-common/src/Plugin.php';
        include_once \dirname(__DIR__, 4).'/vendor/php-http/client-common/src/Plugin/ContentLengthPlugin.php';
        include_once \dirname(__DIR__, 4).'/vendor/php-http/client-common/src/Plugin/RedirectPlugin.php';

        return $container->services['hwi_oauth.http.client'] = new \Http\Client\Common\HttpMethodsClient(($container->privates['Http\\Client\\Common\\PluginClientFactory'] ?? $container->getPluginClientFactoryService())->createClient((new \Http\HttplugBundle\Collector\ProfileClientFactory(new \Http\HttplugBundle\ClientFactory\AutoDiscoveryFactory(), ($container->privates['httplug.collector.collector'] ?? ($container->privates['httplug.collector.collector'] = new \Http\HttplugBundle\Collector\Collector())), ($container->privates['httplug.collector.formatter'] ?? $container->getHttplug_Collector_FormatterService()), ($container->privates['debug.stopwatch'] ?? ($container->privates['debug.stopwatch'] = new \Symfony\Component\Stopwatch\Stopwatch(true)))))->createClient([]), [0 => new \Http\Client\Common\Plugin\ContentLengthPlugin(), 1 => new \Http\Client\Common\Plugin\RedirectPlugin(['preserve_header' => true, 'use_default_for_multiple' => true])], ['client_name' => 'app']), ($container->services['hwi_oauth.http.message_factory'] ?? $container->load('getHwiOauth_Http_MessageFactoryService')));
    }
}
