<?php

namespace ContainerHjoDXgH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHwiOauth_HttpClientService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'hwi_oauth.http_client' shared service.
     *
     * @return \Http\Client\Common\HttpMethodsClient
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/psr/http-client/src/ClientInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/php-http/httplug/src/HttpClient.php';
        include_once \dirname(__DIR__, 4).'/vendor/php-http/client-common/src/HttpMethodsClientInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/php-http/client-common/src/HttpMethodsClient.php';

        return $container->privates['hwi_oauth.http_client'] = new \Http\Client\Common\HttpMethodsClient(($container->services['hwi_oauth.http.client'] ?? $container->load('getHwiOauth_Http_ClientService')), ($container->services['hwi_oauth.http.message_factory'] ?? $container->load('getHwiOauth_Http_MessageFactoryService')));
    }
}
