<?php

namespace ContainerHjoDXgH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUniversity2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.qlZ7sQU.App\Entity\University' shared service.
     *
     * @return \App\Entity\University
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.qlZ7sQU": it references class "App\\Entity\\University" but no such service exists.');
    }
}
