<?php

namespace ContainerHjoDXgH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUniversityController2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\UniversityController' shared autowired service.
     *
     * @return \App\Controller\UniversityController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/UniversityController.php';

        $container->services['App\\Controller\\UniversityController'] = $instance = new \App\Controller\UniversityController(($container->privates['.debug.http_client'] ?? $container->get_Debug_HttpClientService()));

        $instance->setContainer(($container->privates['.service_locator.ULEwkxg'] ?? $container->load('get_ServiceLocator_ULEwkxgService'))->withContext('App\\Controller\\UniversityController', $container));

        return $instance;
    }
}
